---
- hosts: vagrant
  vars:
    ruby: ruby-1.9.2-p180
    phantomjs: phantomjs-1.9.0-linux-x86_64
  tasks:
    - include: tasks/apt.yml
    - include: tasks/ruby.yml
    - include: tasks/shell_setup.yml
    - include: tasks/db.yml
    - include: tasks/phantomjs.yml

    - name: bundle install
      shell: 'executable=/bin/bash chdir=/vagrant . "$HOME/.rvm/scripts/rvm" && bundle'
